---
version: '2'

services:

    web:
        build:
            context: ./build/ruby
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
          - .:/myapp
        ports:
          - "3000:3000"

    postgres:
        image: postgres
        environment:
          POSTGRES_PASSWORD: example

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example